[package]
name = "stio"
version = "0.1.0"
authors = ["Li Jinpei <leekingp1994@163.com>"]
edition = "2018"

[dependencies]
mio = "0.6"

[dependencies.futures]
version = "0.3.0-alpha.11"
package = "futures-preview"

